spring:
  profiles:
    active: default
---
spring:
  profiles: default
server:
  port: 10010
---
server:
  port: 9999
spring:
  profiles: dev
---  
server:
  port: 8888
spring:
  profiles: prod 
---
#person:
#  last-name: Tom
#  age: 18
#  isBoss: false
#  birth: 2004/10/10
#  map: {K1: V1, K2: 2002, K3: true, K4: [W, S, X]}
#  list:
#    - Jax
#    - Fizz
#    - GP
#    - twistFate
#  dog:
#    name: Snoopy
#    age: 5
